name: Build And Test on All OSs
on: [ push, pull_request ]
jobs:
  gradle:
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
        java: [ 11, 17 ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: zulu
          java-version: ${{ matrix.java }}
      - uses: eskatos/gradle-command-action@v1
        with:
          arguments: check fatJar
      - name: Publish Test Report
        if: ${{ always() }}
        uses: mikepenz/action-junit-report@v2
        with:
          report_paths: '**/build/test-results/test/TEST-*.xml'
      - name: Build Rust Client
        working-directory: ./jgrab-client
        run: cargo build
      - name: Smoke Test
        shell: bash
        run: |
          mkdir .jgrab
          cp jgrab-runner/build/libs/jgrab.jar .jgrab/
          jgrab-client/target/debug/jgrab-client -e "2 + 2"
